// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTIjYjiSvLsTPsip2Cw7QwvHPq9rvCGxQ',
    appId: '1:993215685827:web:78cfe7bad8ab81ec6fee76',
    messagingSenderId: '993215685827',
    projectId: 'pet-pals-b6dba',
    authDomain: 'pet-pals-b6dba.firebaseapp.com',
    storageBucket: 'pet-pals-b6dba.appspot.com',
    measurementId: 'G-E6VY05WTJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5M1E578usdIAM86_hdf6738wgY1wklw0',
    appId: '1:993215685827:android:10ddac5cd82beff46fee76',
    messagingSenderId: '993215685827',
    projectId: 'pet-pals-b6dba',
    storageBucket: 'pet-pals-b6dba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCshhD1CK_4TxZZSmUw7Ck2tFmh7hr6_kw',
    appId: '1:993215685827:ios:510dbb96684c86886fee76',
    messagingSenderId: '993215685827',
    projectId: 'pet-pals-b6dba',
    storageBucket: 'pet-pals-b6dba.appspot.com',
    iosBundleId: 'com.petpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCshhD1CK_4TxZZSmUw7Ck2tFmh7hr6_kw',
    appId: '1:993215685827:ios:a07e1e8b3b5c8a0d6fee76',
    messagingSenderId: '993215685827',
    projectId: 'pet-pals-b6dba',
    storageBucket: 'pet-pals-b6dba.appspot.com',
    iosBundleId: 'com.petpals.petPals.RunnerTests',
  );
}
